version: 1.0.{build}

environment:
  matrix:
    - node_version: 20

install:
  - ps: Install-Product node $env:node_version
  - choco install yarn googlechrome --yes
  - yarn install

build: off

test_script:
  # Запуск тестового сервера
  - yarn start
  # Ожидание запуска сервера
  - ps: Start-Sleep -Seconds 10
  # Запуск E2E-тестов
  - yarn test

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn\\Cache"

on_finish:
  - ps: |
      if ($LastExitCode -ne 0) {
        Write-Host "Тесты провалились (код: $LastExitCode)"
        $host.SetShouldExit($LastExitCode)
      } else {
        Write-Host "Все тесты пройдены"
      }
